services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      VITE_PORT: ${VITE_PORT:-5173}
    command: yarn dev --host
