enum SUCCESS_STATUS_CODES {
  CREATE = 201,
  GET = 200,
  UPDATE = 201,
  DELETE = 200,
}

enum ERROR_STATUS_CODES {
  BAD_REQUEST = 400,
  CONFLICT = 409,
  NOT_FOUND = 404,
  UNAUTHORIZED = 401,
  GATEWAY_TIMEOUT = 504,
  INTERNAL_SERVER_ERROR = 500,
  UNAVAILABLE_SERVER = 503,
}

export { SUCCESS_STATUS_CODES, ERROR_STATUS_CODES };
